[2025-06-07T20:32:42.869+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-07T20:32:41.121635+00:00 [queued]>
[2025-06-07T20:32:42.876+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-07T20:32:41.121635+00:00 [queued]>
[2025-06-07T20:32:42.877+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-07T20:32:42.889+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): extract_and_load> on 2025-06-07 20:32:41.121635+00:00
[2025-06-07T20:32:42.896+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2025-06-07T20:32:42.900+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'rss_ingestion_dag', 'extract_and_load', 'manual__2025-06-07T20:32:41.121635+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/rss_ingestion_dag.py', '--cfg-path', '/tmp/tmpr_9a8mhn']
[2025-06-07T20:32:42.903+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask extract_and_load
[2025-06-07T20:32:42.965+0000] {task_command.py:423} INFO - Running <TaskInstance: rss_ingestion_dag.extract_and_load manual__2025-06-07T20:32:41.121635+00:00 [running]> on host dd2d6a82bb53
[2025-06-07T20:32:43.036+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rss_ingestion_dag' AIRFLOW_CTX_TASK_ID='extract_and_load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-07T20:32:41.121635+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-07T20:32:41.121635+00:00'
[2025-06-07T20:32:43.956+0000] {rss_ingestion_dag.py:31} INFO - 0 nouveaux articles sur 29 récupérés (doublons ignorés : 29)
[2025-06-07T20:32:44.247+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2607, in _prep_and_do_upload
    created_json = self._do_upload(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2413, in _do_upload
    response = self._do_multipart_upload(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 1926, in _do_multipart_upload
    response = upload.transmit(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 153, in transmit
    return _request_helpers.wait_and_retry(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/home/airflow/.local/lib/python3.10/site-packages/google/resumable_media/requests/upload.py", line 149, in retriable_request
    self._process_response(result)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/resumable_media/_upload.py", line 125, in _process_response
    _helpers.require_status_code(response, (http.client.OK,), self._get_status_code)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', 200)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rss_ingestion_dag.py", line 35, in extract_and_load
    file_path = upload_to_gcs(articles, bucket_name, prefix)
  File "/opt/airflow/src/utils/gcs_writer.py", line 15, in upload_to_gcs
    blob.upload_from_string(json.dumps(data, ensure_ascii=False, indent=2), content_type='application/json')
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 3059, in upload_from_string
    self.upload_from_file(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2766, in upload_from_file
    self._prep_and_do_upload(
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 2625, in _prep_and_do_upload
    _raise_from_invalid_response(exc)
  File "/home/airflow/.local/lib/python3.10/site-packages/google/cloud/storage/blob.py", line 4791, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.NotFound: 404 POST https://storage.googleapis.com/upload/storage/v1/b/clarifai-news-bucket/raw/o?uploadType=multipart: Not Found: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>)
[2025-06-07T20:32:44.269+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=rss_ingestion_dag, task_id=extract_and_load, execution_date=20250607T203241, start_date=20250607T203242, end_date=20250607T203244
[2025-06-07T20:32:44.280+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 37 for task extract_and_load (404 POST https://storage.googleapis.com/upload/storage/v1/b/clarifai-news-bucket/raw/o?uploadType=multipart: Not Found: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>); 69)
[2025-06-07T20:32:44.318+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-07T20:32:44.334+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
